"""change latitude and longitude to text

Revision ID: 9d20ba7f16c1
Revises: 8b5c5cd24625
Create Date: 2026-05-11 15:46:56.602844

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9d20ba7f16c1'
down_revision: str | None = '8b5c5cd24625'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event_records', 'decimallatitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('event_records', 'decimallongitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event_records', 'decimallongitude',
               existing_type=sa.Text(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('event_records', 'decimallatitude',
               existing_type=sa.Text(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    # ### end Alembic commands ###
